
from enum import Enum


class MenuCommandsConstants(Enum):
    MORPHOLOGY_COMMAND_PAYLOAD = 'MORPHOLOGY_PAYLOAD'
    THRESHOLD_COMMAND_PAYLOAD = 'THRESHOLD_PAYLOAD'
    INTERPOLATION_COMMAND_PAYLOAD = 'INTERPOLATION_PAYLOAD'


